/*
Challenge Rating = {
        cr: Challenge rating selected,
        Use the high value for the NPC’s best attacks and the low value for the rest. Use one value for all ranged attacks and the other for all melee attacks (you generally don’t need to worry about differences between one weapon and another in the same category).        
        highAttackBonus: ,
        lowAttackBonus: ,
        For a damage dice of 2d6, 2 is the number of dice, while 6 is the dice type. The damage bonus is generally equal to the creatures CR if > 1
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamage:NumberDice ,''
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: ''
    }
*/
/*
let combatantArrayAttackStatistics = [
    crThird = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crHalf = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crOne = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwo = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crThree = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',

    },
    crFour = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crFive = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crSix = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crSeven = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crEight = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crNine = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crEleven = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwelve = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crThirteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crFourteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crFifteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crSixteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crSeventeen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crEighteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crNineteen = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwenty = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwentyOne = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwentyTwo = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwentyThree = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwentyFour = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
    crTwentyFive = {
        cr: '',
        highAttackBonus: ,
        lowAttackBonus: ,
        energyRangedDamageNumberDice: '',
        energyRangedDamageDiceType: '',
        kineticRangedDamageNumberDice: '',
        kineticRangedDamageDiceType: '',
        standardMeleeDamageNumberDice: '',
        standardMeleeDamageDiceType: '',
        threeAttacksMeleeDamageNumberDice: '',
        threeAttacksMeleeDamageDiceType: '',
        fourAttacksMeleeDamageNumberDice: '',
        fourAttacksMeleeDamageDiceType: '',
        damageBonus: '',
    },
]
*/