/*
Challenge Rating: {
        eAC: Energy Armor Class,
        kAC: Kenetic Armor Class,
        fort: Fortitude Saving Throw,
        ref: Reflex Saving Throw,
        will: Will Saving Throw,
        hitPoints: Hit Points,
        abilityDC: Ability Difficulty Class,
        baseSpellDC: Base Spell Difficulty Class,
        abilityScoreModifiers: [ Three scores to add to standard ability score array ],
        specialAbilities: Number of available Special Abilities,
        masterSkills:[ To be added to the best skill, Number of master skills to select (3 is standard, however it can be increased) ],
        goodSkills: [ To be added to the next best skills, Number of good skills to select (2 is standard, however it can be increased) ]
    }
*/

let expertArrayMainStatistics= {
    crThird: {
        eAC: 10,
        kAC: 11,
        fort: 0,
        ref: 0,
        will: 2,
        hitPoints: 6,
        abilityDC: 10,
        baseSpellDC: 10,
        abilityScoreModifiers: [ 3, 1, 0 ],
        specialAbilities: 1,
        masterSkills: [ 7, 3 ],
        goodSkills: [ 3, 2 ]
    },
    crHalf: {
        eAC: 10,
        kAC: 11,
        fort: 0,
        ref: 0,
        will: 3,
        hitPoints: 12,
        abilityDC: 11,
        baseSpellDC: 11,
        abilityScoreModifiers: [ 3, 2, 1],
        specialAbilities: 1,
        masterSkills: [ 9, 3 ],
        goodSkills: [ 4, 2 ]
    },
    crOne: {
        eAC: 11,
        kAC: 12,
        fort: 1,
        ref: 1,
        will: 4,
        hitPoints: 17,
        abilityDC: 12,
        baseSpellDC: 11,
        abilityScoreModifiers: [4, 2, 1],
        specialAbilities: 1,
        masterSkills: [ 10, 3 ],
        goodSkills: [ 5, 2 ]
    },
    crTwo: {
        eAC: 13,
        kAC: 14,
        fort: 1,
        ref: 1,
        will: 5,
        hitPoints: 23,
        abilityDC: 13,
        baseSpellDC: 12,
        abilityScoreModifiers: [ 4, 2, 1 ],
        specialAbilities: 1,
        masterSkills: [ 12, 3 ],
        goodSkills: [ 7, 2 ]
    },
    crThree: {
        eAC: 14,
        kAC: 15,
        fort: 2,
        ref: 2,
        will: 6,
        hitPoints: 35,
        abilityDC: 14,
        baseSpellDC: 13,
        abilityScoreModifiers: [4, 2, 1 ],
        specialAbilities: 2,
        masterSkills: [ 13, 3 ],
        goodSkills: [ 8, 2 ]
    },
    crFour: {
        eAC: 16,
        kAC: 17,
        fort: 3,
        ref: 3,
        will: 7,
        hitPoints: 45,
        abilityDC: 15,
        baseSpellDC: 13,
        abilityScoreModifiers: [ 5, 3, 1 ],
        specialAbilities: 2,
        masterSkills: [ 15 , 3 ],
        goodSkills: [ 10 , 2 ]
    },
    crFive: {
        eAC: 17,
        kAC: 18,
        fort: 4,
        ref: 4,
        will: 8,
        hitPoints: 65,
        abilityDC: 15,
        baseSpellDC: 13,
        abilityScoreModifiers: [ 5, 3, 2 ],
        specialAbilities: 2,
        masterSkills: [ 16, 3 ],
        goodSkills: [ 11, 2 ]
    },
    crSix: {
        eAC: 18,
        kAC: 19,
        fort: 5,
        ref: 5,
        will: 9,
        hitPoints: 80,
        abilityDC: 16,
        baseSpellDC: 14,
        abilityScoreModifiers: [ 5, 3, 2 ],
        specialAbilities: 2,
        masterSkills: [ 18, 3 ],
        goodSkills: [ 13, 2 ]
    },
    crSeven: {
        eAC: 19,
        kAC: 20,
        fort: 6,
        ref: 6,
        will: 10,
        hitPoints: 100,
        abilityDC: 17,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 5, 4, 2 ],
        specialAbilities: 2,
        masterSkills: [ 19, 3 ],
        goodSkills: [ 14, 2 ]
    },
    crEight: {
        eAC: 20,
        kAC: 21,
        fort: 7,
        ref: 7,
        will: 11,
        hitPoints: 115,
        abilityDC: 18,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 6, 4, 2 ],
        specialAbilities: 2,
        masterSkills: [ 21, 3 ],
        goodSkills: [ 16, 2 ]
    },
    crNine: {
        eAC: 22,
        kAC: 23,
        fort: 8,
        ref: 8,
        will: 12,
        hitPoints: 135,
        abilityDC: 18,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 6, 4, 3 ],
        specialAbilities: 2,
        masterSkills: [ 22, 3 ],
        goodSkills: [ 17, 2 ]
    },
    crTen: {
        eAC: 23,
        kAC: 24,
        fort: 9,
        ref: 9,
        will: 13,
        hitPoints: 150,
        abilityDC: 19,
        baseSpellDC: 16,
        abilityScoreModifiers: [ 8, 5, 3 ],
        specialAbilities: 2,
        masterSkills: [ 24, 3 ],
        goodSkills: [ 19, 2 ]
    },
    crEleven: {
        eAC: 24,
        kAC: 25,
        fort: 10,
        ref: 10,
        will: 14,
        hitPoints: 170,
        abilityDC: 20,
        baseSpellDC: 16,
        abilityScoreModifiers: [ 8, 5, 3 ],
        specialAbilities: 2,
        masterSkills: [ 25, 3 ],
        goodSkills: [ 20, 2 ]
    },
    crTwelve: {
        eAC: 26,
        kAC: 27,
        fort: 11,
        ref: 11,
        will: 15,
        hitPoints: 185,
        abilityDC: 21,
        baseSpellDC: 17,
        abilityScoreModifiers: [ 8, 5, 4 ],
        specialAbilities: 3,
        masterSkills: [ 27, 3 ],
        goodSkills: [ 22, 2 ]
    },
    crThirteen: {
        eAC: 27,
        kAC: 28,
        fort: 12,
        ref: 12,
        will: 16,
        hitPoints: 210,
        abilityDC: 21,
        baseSpellDC: 17,
        abilityScoreModifiers: [ 8, 6, 4 ],
        specialAbilities: 3,
        masterSkills: [ 28, 3 ],
        goodSkills: [ 23, 2 ]
    },
    crFourteen: {
        eAC: 28,
        kAC: 29,
        fort: 12,
        ref: 12,
        will: 17,
        hitPoints: 235,
        abilityDC: 22,
        baseSpellDC: 17,
        abilityScoreModifiers: [ 8, 6, 4 ],
        specialAbilities: 3,
        masterSkills: [ 30, 3 ],
        goodSkills: [ 25, 2 ]
    },
    crFifteen: {
        eAC: 29,
        kAC: 30,
        fort: 13,
        ref: 13,
        will: 18,
        hitPoints: 255,
        abilityDC: 23,
        baseSpellDC: 18,
        abilityScoreModifiers: [ 9, 7, 5 ],
        specialAbilities: 3,
        masterSkills: [ 31, 3 ],
        goodSkills: [ 26, 2 ]
    },
    crSixteen: {
        eAC: 30,
        kAC: 31,
        fort: 14,
        ref: 14,
        will: 19,
        hitPoints: 280,
        abilityDC: 24,
        baseSpellDC: 18,
        abilityScoreModifiers: [ 10, 7, 5 ],
        specialAbilities: 3,
        masterSkills: [ 33, 3 ],
        goodSkills: [ 28, 2 ]
    },
    crSeventeen: {
        eAC: 31,
        kAC: 32,
        fort: 15,
        ref: 15,
        will: 20,
        hitPoints: 315,
        abilityDC: 24,
        baseSpellDC: 18,
        abilityScoreModifiers: [ 11, 8, 5 ],
        specialAbilities: 3,
        masterSkills: [ 34, 3 ],
        goodSkills: [ 29, 2 ]
    },
    crEighteen: {
        eAC: 32,
        kAC: 33,
        fort: 16,
        ref: 16,
        will: 20,
        hitPoints: 350,
        abilityDC: 25,
        baseSpellDC: 19,
        abilityScoreModifiers: [ 11, 8, 6 ],
        specialAbilities: 3,
        masterSkills: [ 36, 3 ],
        goodSkills: [ 31, 2 ]
    },
    crNineteen: {
        eAC: 33,
        kAC: 34,
        fort: 16,
        ref: 16,
        will: 21,
        hitPoints: 385,
        abilityDC: 26,
        baseSpellDC: 20,
        abilityScoreModifiers: [ 11, 9, 6 ],
        specialAbilities: 4,
        masterSkills: [ 37, 3 ],
        goodSkills: [ 32, 2 ]
    },
    crTwenty: {
        eAC: 35,
        kAC: 36,
        fort: 17,
        ref: 17,
        will: 22,
        hitPoints: 430,
        abilityDC: 27,
        baseSpellDC: 21,
        abilityScoreModifiers: [ 12, 9, 6 ],
        specialAbilities: 4,
        masterSkills: [ 39, 3 ],
        goodSkills: [ 34, 2 ]
    },
    crTwentyOne: {
        eAC: 36,
        kAC: 37,
        fort: 18,
        ref: 18,
        will: 23,
        hitPoints: 465,
        abilityDC: 27,
        baseSpellDC: 21,
        abilityScoreModifiers: [ 12, 10, 7 ],
        specialAbilities: 4,
        masterSkills: [ 40, 3 ],
        goodSkills: [ 35, 2 ]
    },
    crTwentyTwo: {
        eAC: 38,
        kAC: 39,
        fort: 18,
        ref: 18,
        will: 23,
        hitPoints: 500,
        abilityDC: 28,
        baseSpellDC: 22,
        abilityScoreModifiers: [ 13, 10, 7 ],
        specialAbilities: 4,
        masterSkills: [ 42, 3 ],
        goodSkills: [ 37, 2 ]
    },
    crTwentyThree: {
        eAC: 39,
        kAC: 40,
        fort: 19,
        ref: 19,
        will: 24,
        hitPoints: 550,
        abilityDC: 29,
        baseSpellDC: 23,
        abilityScoreModifiers: [ 13, 11, 7 ],
        specialAbilities: 4,
        masterSkills: [ 43, 3 ],
        goodSkills: [ 38, 2 ]
    },
    crTwentyFour: {
        eAC: 41,
        kAC: 42,
        fort: 20,
        ref: 20,
        will: 25,
        hitPoints: 600,
        abilityDC: 30,
        baseSpellDC: 24,
        abilityScoreModifiers: [ 15, 11, 8 ],
        specialAbilities: 4,
        masterSkills: [ 45, 3 ],
        goodSkills: [ 40, 2 ]
    },
    crTwentyFive: {
        eAC: 42,
        kAC: 43,
        fort: 21,
        ref: 21,
        will: 26,
        hitPoints: 650,
        abilityDC: 30,
        baseSpellDC: 24,
        abilityScoreModifiers: [ 15, 12, 8 ],
        specialAbilities: 4,
        masterSkills: [ 46, 3 ],
        goodSkills: [ 41, 2 ]
    },
}