let creatureList = [
    creature ={
        name: 'Drift Leech',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Drift%20Leech&Family=None',
    },
    creature ={
        name: 'Tiny Elemental',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Tiny%20Elemental&Family=Elemental',
    },
    creature ={
        name: 'Goblin (Space)',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Space%20Goblin%20Zaperator&Family=Goblin%20(Space)',
    },
    creature ={
        name: 'Small Herd Animal',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Small%20Herd%20Animal&Family=Herd%20Animal',
    },
    creature ={
        name: 'Hobgar',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Hobgar&Family=None',
    },
    creature ={
        name: 'Khefak ',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Khefak&Family=Khefak',
    },
    creature ={
        name: 'Small Predator',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Small%20Predator&Family=Predator',
    },
    creature ={
        name: 'Skittermander Whelp',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Skittermander%20Whelp&Family=Skittermander',
    },
    creature ={
        name: 'Squox',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Squox&Family=Squox',
    },
    creature ={
        name: 'Symbiend',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Symbiend&Family=Symbiend',
    },
    creature ={
        name: 'Anacite Wingbot',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Wingbot&Family=Anacite',
    },
    creature ={
        name: 'Con Artist',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Con%20Artist&Family=Charlatans',
    },
    creature ={
        name: '',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: '',
    },
    creature ={
        name: 'Damai',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Damai&Family=Damai',
    },
    creature ={
        name: 'Devil, Lemure',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Lemure&Family=Devil',
    },
    creature ={
        name: 'Diatha',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Diatha&Family=Diatha',
    },
    creature ={
        name: 'Drift Mote',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Drift%20Mote&Family=None',
    },
    // Pick up 1/2 with Dromada
    creature ={
        name: 'Agathion, Vicunal',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Vicunal&Family=Agathion',
    },
    creature ={
        name: 'Akata',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Akata&Family=Akata',
    },
    creature ={
        name: 'Akata, Void Zombie',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Void%20Zombie&Family=Akata',
    },
    creature ={
        name: 'Anacite, Dustar',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Dustar&Family=Anacite',
    },
    creature ={
        name: 'Assembly Ooze',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Assembly%20Ooze&Family=None',
    },
    // Pick up 1 with Astriapi, Astriapi Defender
    creature ={
        name: 'Aerial Devil',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aerial%20Devil&Family=None',
    },
    creature ={
        name: 'Apari Constituent',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Apari%20Constituent&Family=Apari',
    },
    creature ={
        name: 'Azer',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Azer&Family=None',
    },
    creature ={
        name: 'Barathu (Early Stage)',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Barathu%20(Early%20Stage)&Family=Barathu',
    },
    creature ={
        name: 'Bolida Miner',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bolida%20Miner&Family=Bolida',
    },
    // Pick up 2 with Celebrities, Streamer
    creature ={
        name: 'Aeon Guard',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aeon%20Guard&Family=Aeon%20Guard',
    },
    creature ={
        name: 'Anacite, Monitor',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Monitor&Family=Anacite',
    },
    creature ={
        name: 'Anacite, Sentry',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Sentry&Family=Anacite',
    },
    creature ={
        name: 'Arabuk, Yearling',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Yearling&Family=Arabuk',
    },
    creature ={
        name: 'Atlapak, Juvenile',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Juvenile&Family=Atlapak',
    },
    // Pick up 3 with Autofly Swarm
    creature ={
        name: 'Aanung-an',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aanung-an&Family=None',
    },
    creature ={
        name: 'Arquand Gazelle',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Arquand%20Gazelle&Family=None',
    },
    creature ={
        name: 'Barghest',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Barghest&Family=None',
    },
    creature ={
        name: 'Uplifted Bear Avenger',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Uplifted%20Bear%20Avenger&Family=Bear%20(Uplifted)',
    },
    creature ={
        name: 'Cargo Creep',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Cargo%20Creep&Family=None',
    },
    // Pick up 4 with Carrion Dreg
    creature ={
        name: 'Aglian Collective',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aglian%20Collective&Family=None',
    },
    creature ={
        name: 'Alkainan',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Alkainan&Family=None',
    },
    creature ={
        name: 'Anassanoi',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anassanoi&Family=None',
    },
    creature ={
        name: 'Animated Armor, Animated Lictor Hellknight Plate',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Animated%20Lictor%20Hellknight%20Plate&Family=Animated%20Armor',
    },
    creature ={
        name: 'Archon, Power',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Power%20Archon&Family=Archon',
    },
    // Pick up 5 with Assassins, Masked Assassin
    creature ={
        name: 'Agathion, Claustral',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Claustral&Family=Agathion',
    },
    creature ={
        name: 'Agathion, Mustyotal',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Mustyotal&Family=Agathion',
    },
    creature ={
        name: 'Anacite Quantifier',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Quantifier&Family=None',
    },
    creature ={
        name: 'Anacite Ambassador',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Ambassador&Family=Anacite',
    },
    creature ={
        name: 'Arcane Asp',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Arcane%20Asp&Family=None',
    },
    // Pick up 6 with Astriapi, Astriapi Warden
    creature ={
        name: '',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: '',
    },
]

module.exports = creatureList;