let creature = {}

export let creatureList = [
    creature ={
        name: 'Drift Leech',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Drift%20Leech&Family=None',
    },
    creature ={
        name: 'Tiny Elemental',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Tiny%20Elemental&Family=Elemental',
    },
    creature ={
        name: 'Goblin (Space)',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Space%20Goblin%20Zaperator&Family=Goblin%20(Space)',
    },
    creature ={
        name: 'Small Herd Animal',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Small%20Herd%20Animal&Family=Herd%20Animal',
    },
    creature ={
        name: 'Hobgar',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Hobgar&Family=None',
    },
    creature ={
        name: 'Khefak ',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Khefak&Family=Khefak',
    },
    creature ={
        name: 'Small Predator',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Small%20Predator&Family=Predator',
    },
    creature ={
        name: 'Skittermander Whelp',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Skittermander%20Whelp&Family=Skittermander',
    },
    creature ={
        name: 'Squox',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Squox&Family=Squox',
    },
    creature ={
        name: 'Symbiend',
        creatureCR:'1/3',
        crInt: 0.3,
        exp: 135,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Symbiend&Family=Symbiend',
    },
    creature ={
        name: 'Anacite Wingbot',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Wingbot&Family=Anacite',
    },
    creature ={
        name: 'Con Artist',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Con%20Artist&Family=Charlatans',
    },
    creature ={
        name: 'Damai',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Damai&Family=Damai',
    },
    creature ={
        name: 'Devil, Lemure',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Lemure&Family=Devil',
    },
    creature ={
        name: 'Diatha',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Diatha&Family=Diatha',
    },
    creature ={
        name: 'Drift Mote',
        creatureCR:'1/2',
        crInt: 0.5,
        exp: 200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Drift%20Mote&Family=None',
    },
    // Pick up 1/2 with Dromada
    creature ={
        name: 'Agathion, Vicunal',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Vicunal&Family=Agathion',
    },
    creature ={
        name: 'Akata',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Akata&Family=Akata',
    },
    creature ={
        name: 'Akata, Void Zombie',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Void%20Zombie&Family=Akata',
    },
    creature ={
        name: 'Anacite, Dustar',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Dustar&Family=Anacite',
    },
    creature ={
        name: 'Assembly Ooze',
        creatureCR:'1',
        crInt: 1.0,
        exp: 400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Assembly%20Ooze&Family=None',
    },
    // Pick up 1 with Astriapi, Astriapi Defender
    creature ={
        name: 'Aerial Devil',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aerial%20Devil&Family=None',
    },
    creature ={
        name: 'Apari Constituent',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Apari%20Constituent&Family=Apari',
    },
    creature ={
        name: 'Azer',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Azer&Family=None',
    },
    creature ={
        name: 'Barathu (Early Stage)',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Barathu%20(Early%20Stage)&Family=Barathu',
    },
    creature ={
        name: 'Bolida Miner',
        creatureCR:'2',
        crInt: 2.0,
        exp: 600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bolida%20Miner&Family=Bolida',
    },
    // Pick up 2 with Celebrities, Streamer
    creature ={
        name: 'Aeon Guard',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aeon%20Guard&Family=Aeon%20Guard',
    },
    creature ={
        name: 'Anacite, Monitor',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Monitor&Family=Anacite',
    },
    creature ={
        name: 'Anacite, Sentry',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Sentry&Family=Anacite',
    },
    creature ={
        name: 'Arabuk, Yearling',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Yearling&Family=Arabuk',
    },
    creature ={
        name: 'Atlapak, Juvenile',
        creatureCR:'3',
        crInt: 3.0,
        exp: 800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Juvenile&Family=Atlapak',
    },
    // Pick up 3 with Autofly Swarm
    creature ={
        name: 'Aanung-an',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aanung-an&Family=None',
    },
    creature ={
        name: 'Arquand Gazelle',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Arquand%20Gazelle&Family=None',
    },
    creature ={
        name: 'Barghest',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Barghest&Family=None',
    },
    creature ={
        name: 'Uplifted Bear Avenger',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Uplifted%20Bear%20Avenger&Family=Bear%20(Uplifted)',
    },
    creature ={
        name: 'Cargo Creep',
        creatureCR:'4',
        crInt: 4.0,
        exp: 1200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Cargo%20Creep&Family=None',
    },
    // Pick up 4 with Carrion Dreg
    creature ={
        name: 'Aglian Collective',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aglian%20Collective&Family=None',
    },
    creature ={
        name: 'Alkainan',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Alkainan&Family=None',
    },
    creature ={
        name: 'Anassanoi',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anassanoi&Family=None',
    },
    creature ={
        name: 'Animated Lictor Hellknight Plate',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Animated%20Lictor%20Hellknight%20Plate&Family=Animated%20Armor',
    },
    creature ={
        name: 'Archon, Power',
        creatureCR:'5',
        crInt: 5.0,
        exp: 1600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Power%20Archon&Family=Archon',
    },
    // Pick up 5 with Assassins, Masked Assassin
    creature ={
        name: 'Agathion, Claustral',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Claustral&Family=Agathion',
    },
    creature ={
        name: 'Agathion, Mustyotal',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Mustyotal&Family=Agathion',
    },
    creature ={
        name: 'Anacite Quantifier',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Quantifier&Family=None',
    },
    creature ={
        name: 'Anacite Ambassador',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Ambassador&Family=Anacite',
    },
    creature ={
        name: 'Arcane Asp',
        creatureCR:'6',
        crInt: 6.0,
        exp: 2400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Arcane%20Asp&Family=None',
    },
    // Pick up 6 with Astriapi, Astriapi Warden
    creature ={
        name: 'Abynthic',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Abynthic&Family=None',
    },
    creature ={
        name: 'Aeon Guard Specialist',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aeon%20Guard%20Specialist&Family=Aeon%20Guard',
    },
    creature ={
        name: 'Aeon Stone Network',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aeon%20Stone%20Network&Family=None',
    },
    creature ={
        name: 'Anacite Laborer',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Laborer&Family=Anacite',
    },
    creature ={
        name: 'Angel, Barachius',
        creatureCR:'7',
        crInt: 7.0,
        exp: 3200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Barachius&Family=Angel',
    },
    // Pick up 7 with Apari
    creature ={
        name: 'Acrochor',
        creatureCR:'8',
        crInt: 8.0,
        exp: 4800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Acrochor&Family=None',
    },
    creature ={
        name: 'Arabuk',
        creatureCR:'8',
        crInt: 8.0,
        exp: 4800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Arabuk&Family=Arabuk',
    },
    creature ={
        name: 'Tritidair',
        creatureCR:'8',
        crInt: 8.0,
        exp: 4800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Tritidair&Family=Azata',
    },
    creature ={
        name: 'Bolida Overseer',
        creatureCR:'8',
        crInt: 8.0,
        exp: 4800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bolida%20Overseer&Family=Bolida',
    },
    creature ={
        name: 'Bone Trooper Captain',
        creatureCR:'8',
        crInt: 8.0,
        exp: 4800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bone%20Trooper%20Captain&Family=Bone%20Trooper',
    },
    // pick up 8 with Brain Collector
    creature ={
        name: 'Viper',
        creatureCR:'9',
        crInt: 9.0,
        exp: 6400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Viper&Family=Assassins',
    },
    creature ={
        name: 'Atlapak',
        creatureCR:'9',
        crInt: 9.0,
        exp: 6400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Atlapak&Family=Atlapak',
    },
    creature ={
        name: 'Balrodd',
        creatureCR:'9',
        crInt: 9.0,
        exp: 6400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Balrodd&Family=None',
    },
    creature ={
        name: 'Baykok',
        creatureCR:'9',
        crInt: 9.0,
        exp: 6400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Baykok&Family=None',
    },
    creature ={
        name: 'Cerebric Fungus Voyager',
        creatureCR:'9',
        crInt: 9.0,
        exp: 6400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Cerebric%20Fungus%20Voyager&Family=Cerebric%20Fungus',
    },
    // Pick up 9 with Data-Corrupted Creature, Data-Corrputed SRO
    creature ={
        name: 'Tekhoinos',
        creatureCR:'10',
        crInt: 10.0,
        exp: 9600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Tekhoinos&Family=Aeon',
    },
    creature ={
        name: 'Anacite Predator Drone',
        creatureCR:'10',
        crInt: 10.0,
        exp: 9600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anacite%20Predator%20Drone&Family=Anacite',
    },
    creature ={
        name: 'Ashypsozoan',
        creatureCR:'10',
        crInt: 10.0,
        exp: 9600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Ashypsozoan&Family=None',
    },
    creature ={
        name: 'Atrocite',
        creatureCR:'10',
        crInt: 10.0,
        exp: 9600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Atrocite&Family=None',
    },
    creature ={
        name: 'Bodysnatcher Autocrat',
        creatureCR:'10',
        crInt: 10.0,
        exp: 9600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bodysnatcher%20Autocrat&Family=Bodysnatcher%20Slime',
    },
    // Pick up 10 with Bounty Hunters, Bounty Hunter
    creature ={
        name: 'Animated Quartz Swarm',
        creatureCR:'11',
        crInt: 11.0,
        exp: 12800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Animated%20Quartz%20Swarm&Family=None',
    },
    creature ={
        name: 'Carnivorous Crystal',
        creatureCR:'11',
        crInt: 11.0,
        exp: 12800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Carnivorous%20Crystal&Family=None',
    },
    creature ={
        name: 'Daemon, Palioxodaemon',
        creatureCR:'11',
        crInt: 11.0,
        exp: 12800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Palioxodaemon&Family=Daemon',
    },
    creature ={
        name: 'Defrex',
        creatureCR:'11',
        crInt: 11.0,
        exp: 12800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Defrex&Family=Defrex',
    },
    creature ={
        name: 'Demon, Prexian Mutantspawn',
        creatureCR:'11',
        crInt: 11.0,
        exp: 12800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Prexian%20Mutantspawn&Family=Demon',
    },
    // Pick up 11 with Diplomats, Plenipotentiary
    creature ={
        name: 'AHAV',
        creatureCR:'12',
        crInt: 12.0,
        exp: 19200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=AHAV&Family=None',
    },
    creature ={
        name: 'Anemonite Communicant',
        creatureCR:'12',
        crInt: 12.0,
        exp: 19200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Anemonite%20Communicant&Family=None',
    },
    creature ={
        name: 'Asteray',
        creatureCR:'12',
        crInt: 12.0,
        exp: 19200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Asteray&Family=None',
    },
    creature ={
        name: 'Daemon, Alorbidaemon',
        creatureCR:'12',
        crInt: 12.0,
        exp: 19200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Alorbidaemon&Family=Daemon',
    },
    creature ={
        name: 'Damai Guardian',
        creatureCR:'12',
        crInt: 12.0,
        exp: 19200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Damai%20Guardian&Family=Damai',
    },
    // Pick up 12 with Deadfall Stalker
    creature ={
        name: 'Amp-lion',
        creatureCR:'13',
        crInt: 13.0,
        exp: 25600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Amp-lion&Family=None',
    },
    creature ={
        name: 'Astro-krill Swarm',
        creatureCR:'13',
        crInt: 13.0,
        exp: 25600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Astro-krill%20Swarm&Family=None',
    },
    creature ={
        name: 'Avigwyr',
        creatureCR:'13',
        crInt: 13.0,
        exp: 25600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Avigwyr&Family=Azata',
    },
    creature ={
        name: 'Cable Serpent',
        creatureCR:'13',
        crInt: 13.0,
        exp: 25600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Cable%20Serpent&Family=None',
    },
    creature ={
        name: 'Cloud Ray',
        creatureCR:'13',
        crInt: 13.0,
        exp: 25600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Cloud%20Ray&Family=Cloud%20Ray',
    },
    // Pick up 13 with Demon, Pluprex
    creature ={
        name: 'Deadeye',
        creatureCR:'14',
        crInt: 14.0,
        exp: 38400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Deadeye&Family=Assassins',
    },
    creature ={
        name: 'Notorious Bounty Hunter',
        creatureCR:'14',
        crInt: 14.0,
        exp: 38400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Notorious%20Bounty%20Hunter&Family=Bounty%20Hunters',
    },
    creature ={
        name: 'Ichor Wheel',
        creatureCR:'14',
        crInt: 14.0,
        exp: 38400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Ichor%20Wheel&Family=Carrion%20Wheel',
    },
    creature ={
        name: 'Death Cruiser ',
        creatureCR:'14',
        crInt: 14.0,
        exp: 38400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Death%20Cruiser&Family=None',
    },
    creature ={
        name: 'Deh-Nolo',
        creatureCR:'14',
        crInt: 14.0,
        exp: 38400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Deh-Nolo&Family=None',
    },
    // Pick up 14 with Dragon (Metallic), Adult Silver Dragon
    creature ={
        name: 'Aegis Protocol',
        creatureCR:'15',
        crInt: 15.0,
        exp: 51200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aegis%20Protocol&Family=None',
    },
    creature ={
        name: 'Bryrvath',
        creatureCR:'15',
        crInt: 15.0,
        exp: 51200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Bryrvath&Family=None',
    },
    creature ={
        name: 'Mature Adult Horacalcum Dragon',
        creatureCR:'15',
        crInt: 15.0,
        exp: 51200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Mature%20Adult%20Horacalcum%20Dragon&Family=Dragon%20(Starmetal)',
    },
    creature ={
        name: 'Equinoxian Apastra',
        creatureCR:'15',
        crInt: 15.0,
        exp: 51200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Equinoxian%20Apastra&Family=Equinoxian',
    },
    creature ={
        name: 'Flayer Leech Effigy',
        creatureCR:'15',
        crInt: 15.0,
        exp: 51200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Flayer%20Leech%20Effigy&Family=Flayer%20Leech',
    },
    // Pick up 15 with Giant, Moon Giant
    creature ={
        name: 'Animated Lashunta Mind Mail III',
        creatureCR:'16',
        crInt: 16.0,
        exp: 76800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Animated%20Lashunta%20Mind%20Mail%20III&Family=Animated%20Armor',
    },
    creature ={
        name: 'Aqlath',
        creatureCR:'16',
        crInt: 16.0,
        exp: 76800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Aqlath&Family=None',
    },
    creature ={
        name: 'Fire Whale',
        creatureCR:'16',
        crInt: 16.0,
        exp: 76800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Fire%20Whale&Family=None',
    },
    creature ={
        name: 'Spec-ops Veteran',
        creatureCR:'16',
        crInt: 16.0,
        exp: 76800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Spec-ops%20Veteran&Family=Former%20Military',
    },
    creature ={
        name: 'Haeshi-Shaa (Shaa Form)',
        creatureCR:'16',
        crInt: 16.0,
        exp: 76800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Haeshi-Shaa%20(Shaa%20Form)&Family=Haeshi-Shaa',
    },
    // pick up 16 with Kami, Chinjugami
    creature ={
        name: 'Angel, Exodus',
        creatureCR:'17',
        crInt: 17.0,
        exp: 102400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Exodus&Family=Angel',
    },
    creature ={
        name: 'Calecor',
        creatureCR:'17',
        crInt: 17.0,
        exp: 102400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Calecor&Family=None',
    },
    creature ={
        name: 'Diaspora Wyrm Saga',
        creatureCR:'17',
        crInt: 17.0,
        exp: 102400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Diaspora%20Wyrm%20Saga&Family=Diaspora%20Wyrm',
    },
    creature ={
        name: 'Emotivore Mastermind',
        creatureCR:'17',
        crInt: 17.0,
        exp: 102400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Emotivore%20Mastermind&Family=Emotivore',
    },
    creature ={
        name: 'Formian Queen',
        creatureCR:'17',
        crInt: 17.0,
        exp: 102400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Formian%20Queen&Family=Formian',
    },
    // Pick up 17 with Genesis Wraith
    creature ={
        name: 'Specter',
        creatureCR:'18',
        crInt: 18.0,
        exp: 153600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Specter&Family=Assassins',
    },
    creature ={
        name: 'Contemplative Mentor',
        creatureCR:'18',
        crInt: 18.0,
        exp: 153600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Contemplative%20Mentor&Family=Contemplative',
    },
    creature ={
        name: 'Daemon, Adikodaemon',
        creatureCR:'18',
        crInt: 18.0,
        exp: 153600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Adikodaemon&Family=Daemon',
    },
    creature ={
        name: 'Old Void Dragon',
        creatureCR:'18',
        crInt: 18.0,
        exp: 153600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Old%20Void%20Dragon&Family=Dragon%20(Outer)',
    },
    creature ={
        name: 'Exhaust Ooze',
        creatureCR:'18',
        crInt: 18.0,
        exp: 153600,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Exhaust%20Ooze&Family=None',
    },
    // Pick up 18 with Ghigorda
    creature ={
        name: 'Devil, Endbringer Devil (Dhalochar)',
        creatureCR:'19',
        crInt: 19.0,
        exp: 204800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Endbringer%20Devil%20(Dhalochar)&Family=Devil',
    },
    creature ={
        name: 'Frujai Colony',
        creatureCR:'19',
        crInt: 19.0,
        exp: 204800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Frujai%20Colony&Family=Frujai',
    },
    creature ={
        name: 'Giant, Eclipse',
        creatureCR:'19',
        crInt: 19.0,
        exp: 204800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Eclipse&Family=Giant',
    },
    creature ={
        name: 'Mahadatari',
        creatureCR:'19',
        crInt: 19.0,
        exp: 204800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Mahadatari&Family=None',
    },
    creature ={
        name: 'Many-miened One',
        creatureCR:'19',
        crInt: 19.0,
        exp: 204800,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Many-miened%20One&Family=None',
    },
    // Pick up 19 with Solar Wisp, Mature Solar Wisp
    creature ={
        name: 'Brood Sovereign',
        creatureCR:'20',
        crInt: 20.0,
        exp: 307200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Brood%20Sovereign&Family=None',
    },
    creature ={
        name: 'Kyokor',
        creatureCR:'20',
        crInt: 20.0,
        exp: 307200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Kyokor&Family=None',
    },
    creature ={
        name: 'Living Apocalypse',
        creatureCR:'20',
        crInt: 20.0,
        exp: 307200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Living%20Apocalypse&Family=None',
    },
    creature ={
        name: 'Divine Avatar',
        creatureCR:'20',
        crInt: 20.0,
        exp: 307200,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Divine%20Avatar&Family=Religious%20Figures',
    },
    creature ={
        name: 'Rendalairn',
        creatureCR:'25',
        crInt: 25.0,
        exp: 1638400,
        link: 'https://www.aonsrd.com/AlienDisplay.aspx?ItemName=Rendalairn&Family=None',
    },
]
