/*
    arr = {
        cr: Challenge rating selected,
        xp: Experience awarded,
        eAC: Energy Armor Class,
        kAC: Kenetic Armor Class,
        fort: Fortitude Saving Throw,
        ref: Reflex Saving Throw,
        will: Will Saving Throw,
        hitPoints: Hit Points,
        abilityDC: Ability Difficulty Class,
        baseSpellDC: Base Spell Difficulty Class,
        abilityScoreModifiers: [ Three scores to add to standard ability score array ],
        specialAbilities: Number of available Special Abilities,
        masterSkills:[ To be added to the best skill, Number of master skills to select (1 is standard, however it can be increased) ],
        goodSkills: [ To be added to the next best skills, Number of good skills to select (2 is standard, however it can be increased) ]
    }
*/

let arr = {};

var combatantArrayMainStatistics = [
    arr = {
        cr: '1/3',
        xp: 135,
        eAC: 10,
        kAC: 12,
        fort: 1,
        ref: 1,
        will: 0,
        hitPoints: 6,
        abilityDC: 8,
        baseSpellDC: 8,
        abilityScoreModifiers:[ 3, 1, 0 ],
        specialAbilities: 1,
        masterSkills:[ 7, 1 ],
        goodSkills: [ 3, 2 ]
    },
    arr = {
        cr: '1/2',
        xp: 200,
        eAC: 10,
        kAC: 12,
        fort: 2,
        ref: 2,
        will: 0,
        hitPoints: 13,
        abilityDC: 9,
        baseSpellDC: 9,
        abilityScoreModifiers: [ 3, 2, 1 ],
        specialAbilities: 1,
        masterSkills: [ 9, 1 ],
        goodSkills: [ 4 ,2 ]
    },
    arr = {
        cr: '1',
        xp: 400,
        eAC: 11,
        kAC: 13,
        fort: 3,
        ref: 3,
        will: 1,
        hitPoints: 20,
        abilityDC: 10,
        baseSpellDC: 9,
        abilityScoreModifiers: [ 4, 2, 1 ],
        specialAbilities: 1,
        masterSkills: [ 10, 1 ],
        goodSkills: [ 5, 2 ]
    },
    arr = {
        cr: '2',
        xp: 600,
        eAC: 13,
        kAC: 15,
        fort: 4,
        ref: 4,
        will: 1,
        hitPoints: 25,
        abilityDC: 11,
        baseSpellDC: 10,
        abilityScoreModifiers: [ 4, 2, 1 ],
        specialAbilities: 2,
        masterSkills: [ 12, 1 ],
        goodSkills: [ 7, 2 ]
    },
    arr = {
        cr: '3',
        xp: 800,
        eAC: 14,
        kAC: 16,
        fort: 5,
        ref: 5,
        will: 2,
        hitPoints: 40,
        abilityDC: 12,
        baseSpellDC: 11,
        abilityScoreModifiers: [ 4, 2, 1 ],
        specialAbilities: 2,
        masterSkills: [ 13, 1 ],
        goodSkills: [ 8, 2 ]
    },
    arr = {
        cr: '4',
        xp: 1200,
        eAC: 16,
        kAC: 18,
        fort: 6,
        ref: 6,
        will: 3,
        hitPoints: 50,
        abilityDC: 13,
        baseSpellDC: 11,
        abilityScoreModifiers: [ 5, 3, 1 ],
        specialAbilities: 2,
        masterSkills: [ 15, 1 ],
        goodSkills: [ 10, 2 ]
    },
    arr = {
        cr: '5',
        xp: 1600,
        eAC: 17,
        kAC: 19,
        fort: 7,
        ref: 7,
        will: 4,
        hitPoints: 70,
        abilityDC: 13,
        baseSpellDC: 11,
        abilityScoreModifiers: [ 5, 3, 2 ],
        specialAbilities: 2,
        masterSkills: [ 16, 1 ],
        goodSkills: [ 11, 2 ]
    },
    arr = {
        cr: '6',
        xp: 2400,
        eAC: 18,
        kAC: 20,
        fort: 8,
        ref: 8,
        will: 5,
        hitPoints: 90,
        abilityDC: 14,
        baseSpellDC: 12,
        abilityScoreModifiers: [ 5, 3, 2 ],
        specialAbilities: 2,
        masterSkills: [ 18, 1 ],
        goodSkills: [ 13, 2 ]
    },
    arr = {
        cr: '7',
        xp: 3200,
        eAC: 19,
        kAC: 21,
        fort: 9,
        ref: 9,
        will: 6,
        hitPoints: 105,
        abilityDC: 15,
        baseSpellDC: 13,
        abilityScoreModifiers: [ 5, 4, 2 ],
        specialAbilities: 2,
        masterSkills: [ 19, 1 ],
        goodSkills: [ 14, 2 ]
    },
    arr = {
        cr: '8',
        xp: 4800,
        eAC: 20,
        kAC: 22,
        fort: 10,
        ref: 10,
        will: 7,
        hitPoints: 125,
        abilityDC: 16,
        baseSpellDC: 13,
        abilityScoreModifiers: [ 6, 4, 2 ],
        specialAbilities: 2,
        masterSkills: [ 21, 1 ],
        goodSkills: [ 16, 2 ]
    },
    arr = {
        cr: '9',
        xp: 6400,
        eAC: 22,
        kAC: 24,
        fort: 11,
        ref: 11,
        will: 8,
        hitPoints: 145,
        abilityDC: 16,
        baseSpellDC: 13,
        abilityScoreModifiers: [ 6, 4, 3 ],
        specialAbilities: 2,
        masterSkills: [ 22, 1 ],
        goodSkills: [ 17, 2 ]
    },
    arr = {
        cr: '10',
        xp: 9600,
        eAC: 23,
        kAC: 25,
        fort: 12,
        ref: 12,
        will: 9,
        hitPoints: 165,
        abilityDC: 17,
        baseSpellDC: 14,
        abilityScoreModifiers: [ 8, 5, 3 ],
        specialAbilities: 2,
        masterSkills: [ 24, 1 ],
        goodSkills: [ 19, 2 ]
    },
    arr = {
        cr: '11',
        xp: 12800,
        eAC: 24,
        kAC: 26,
        fort: 13,
        ref: 13,
        will: 10,
        hitPoints: 180,
        abilityDC: 18,
        baseSpellDC: 14,
        abilityScoreModifiers: [ 8, 5, 3 ],
        specialAbilities: 2,
        masterSkills: [ 25, 1 ],
        goodSkills: [ 20, 2 ]
    },
    arr = {
        cr: '12',
        xp: 19200,
        eAC: 26,
        kAC: 28,
        fort: 14,
        ref: 14,
        will: 11,
        hitPoints: 200,
        abilityDC: 19,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 8, 5, 4 ],
        specialAbilities: 3,
        masterSkills: [ 27, 1 ],
        goodSkills: [ 22, 2 ]
    },
    arr = {
        cr: '13',
        xp: 25600,
        eAC: 27,
        kAC: 29,
        fort: 15,
        ref: 15,
        will: 12,
        hitPoints: 225,
        abilityDC: 19,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 8, 6, 4 ],
        specialAbilities: 3,
        masterSkills: [ 28, 1 ],
        goodSkills: [ 23, 2 ]
    },
    arr = {
        cr: '14',
        xp: 38400,
        eAC: 28,
        kAC: 30,
        fort: 16,
        ref: 16,
        will: 12,
        hitPoints: 250,
        abilityDC: 20,
        baseSpellDC: 15,
        abilityScoreModifiers: [ 8, 6, 4 ],
        specialAbilities: 3,
        masterSkills: [ 30, 1 ],
        goodSkills: [ 25, 2 ]
    },
    arr = {
        cr: '15',
        xp: 51200,
        eAC: 29,
        kAC: 31,
        fort: 17,
        ref: 17,
        will: 13,
        hitPoints: 275,
        abilityDC: 21,
        baseSpellDC: 16,
        abilityScoreModifiers: [ 9, 7, 5 ],
        specialAbilities: 3,
        masterSkills: [ 31, 1 ],
        goodSkills: [ 26, 2 ]
    },
    arr = {
        cr: '16',
        xp: 76800,
        eAC: 30,
        kAC: 32,
        fort: 18,
        ref: 18,
        will: 14,
        hitPoints: 300,
        abilityDC: 22,
        baseSpellDC: 16,
        abilityScoreModifiers: [ 10, 7, 5 ],
        specialAbilities: 3,
        masterSkills: [ 33, 1 ],
        goodSkills: [ 28, 2 ]
    },
    arr = {
        cr: '17',
        xp: 102400,
        eAC: 31,
        kAC: 33,
        fort: 19,
        ref: 19,
        will: 15,
        hitPoints: 340,
        abilityDC: 22,
        baseSpellDC: 16,
        abilityScoreModifiers: [ 11, 8, 5 ],
        specialAbilities: 3,
        masterSkills: [ 34, 1 ],
        goodSkills: [ 29, 2 ]
    },
    arr = {
        cr: '18',
        xp: 153600,
        eAC: 32,
        kAC: 34,
        fort: 19,
        ref: 19,
        will: 16,
        hitPoints: 375,
        abilityDC: 23,
        baseSpellDC: 17,
        abilityScoreModifiers: [ 11, 8, 6 ],
        specialAbilities: 4,
        masterSkills: [ 36, 1 ],
        goodSkills: [ 32, 2 ]
    },
    arr = {
        cr: '19',
        xp: 204800,
        eAC: 33,
        kAC: 35,
        fort: 20,
        ref: 20,
        will: 16,
        hitPoints: 415,
        abilityDC: 24,
        baseSpellDC: 18,
        abilityScoreModifiers: [ 11, 9, 6 ],
        specialAbilities: 4,
        masterSkills: [ 37, 1 ],
        goodSkills: [ 32, 2 ]
    },
    arr = {
        cr: '20',
        xp: 307200,
        eAC: 35,
        kAC: 37,
        fort: 21,
        ref: 21,
        will: 17,
        hitPoints: 465,
        abilityDC: 25,
        baseSpellDC: 19,
        abilityScoreModifiers: [ 12, 9, 6 ],
        specialAbilities: 4,
        masterSkills: [ 39, 1 ],
        goodSkills: [ 34, 2 ]
    },
    arr = {
        cr: '21',
        xp: 409600,
        eAC: 36,
        kAC: 38,
        fort: 22,
        ref: 22,
        will: 18,
        hitPoints: 500,
        abilityDC: 25,
        baseSpellDC: 19,
        abilityScoreModifiers: [ 12, 10, 7 ],
        specialAbilities: 4,
        masterSkills: [ 40, 1 ],
        goodSkills: [ 35, 2 ]
    },
    arr = {
        cr: '22',
        xp: 614400,
        eAC: 38,
        kAC: 40,
        fort: 22,
        ref: 22,
        will: 18,
        hitPoints: 550,
        abilityDC: 26,
        baseSpellDC: 20,
        abilityScoreModifiers: [ 13, 10, 7 ],
        specialAbilities: 4,
        masterSkills: [ 42, 1 ],
        goodSkills: [ 37 , 2 ]
    },
    arr = {
        cr: '23',
        xp: 819200,
        eAC: 39,
        kAC: 41,
        fort: 23,
        ref: 23,
        will: 19,
        hitPoints: 600,
        abilityDC: 27,
        baseSpellDC: 21,
        abilityScoreModifiers: [ 13, 11, 7 ],
        specialAbilities: 4,
        masterSkills: [ 43, 1 ],
        goodSkills: [ 38, 2 ]
    },
    arr = {
        cr: '24',
        xp: 1228800,
        eAC: 41,
        kAC: 43,
        fort: 24,
        ref: 24,
        will: 20,
        hitPoints: 650,
        abilityDC: 28,
        baseSpellDC: 22,
        abilityScoreModifiers: [15, 11, 8 ],
        specialAbilities: 4,
        masterSkills: [ 45, 1 ],
        goodSkills: [ 40, 2 ]
    },
    arr = {
        cr: '25',
        xp: 1638400,
        eAC: 42,
        kAC: 44,
        fort: 25,
        ref: 25,
        will: 21,
        hitPoints: 700,
        abilityDC: 28,
        baseSpellDC: 22,
        abilityScoreModifiers: [15, 12, 8 ],
        specialAbilities: 4,
        masterSkills: [ 46, 1 ],
        goodSkills: [ 41, 2 ]
    },
];

export {combatantArrayMainStatistics};